# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/allwinner/cupid-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter cupid,$(TARGET_BOARD_PLATFORM)),)

endif
